### ISSUE TITLE
batterynotif(uname).sh only displays the `#Battery Low 1` message.

### ISSUE THREAD

**Issue by cipricus** [jerrinfrncs/batterynotif#1]
First of all: thanks for this nice script!

I have tried to use the `batterynotif(uname).sh` script in Solus, as the acpi one was more problematic, and cron and dcron are not available in Solus ([Solus replacement for 'cron' ?](https://solus-project.com/forums/viewtopic.php?f=14&t=1051&hilit=cron)). It is a great replacement of the  `/etc/UPower/UPower.conf` settings that [do not work for me](https://github.com/budgie-desktop/budgie-desktop/issues/835#issuecomment-289876544) because of a bug or problem involving `gnome-settings-daemon` (as Ikey Doherty [said](https://github.com/budgie-desktop/budgie-desktop/issues/835#issuecomment-289876949)).

It works, but only to a point: what happens is that I only see the "Battery low", that is the message and sound of `#Battery Low 1` repeated again and again after each change of 2% or even 1%, without ever getting to "Battery Critical" or to "About to..." , nor to the `systemctl` action.

**Comment by jerrinfrncs** [comment]
Thanks for testing. I have corrected the issue. Do comment if you have further problems.

**Comment by cipricus** [comment]
I will try to comment if that is useful to you, although I am not mastering the scripting language at all, I can only test the scripts. And I have to test more in order to give you an accurate feedback. But already the script is useful to me.

At the present I can say that _only the first_ of the three `elif` parts is taken into account. In the last form of the uname script that I tested, I think you came to the same conclusion, as you put the shutdown part first (of the three) and that's the one that is triggered.

**Comment by jerrinfrncs** [comment]
Its working perfectly in my end. Can you heck whether the battery level is reported correctly? just compare the value in notifications and system value.

**Comment by cipricus** [comment]
Battery level is reported correctly.

In part it works for me too. But because as far as I can tell for now, as I said, only the first of the three `elif` parts is taken into account, I can achieve my purpose by using two separate versions of the script at he same time, each containing a different `elif` part, one to signal low battery repeatedly under a given level (as indicated in my initial post here), and a second that just puts the computer to sleep at the lowest level.

After more testing I see that  on my system the only action that is triggered is that after the `elif` line _with the biggest number_: it's not the order of those lines, is the number that counts. 

For example, in this case

```
elif [ $battery_level -le 10 -a $STATUS = $NOT_CHARGING ] #Battery Low 
then
/usr/bin/notify-send -i "$ICONL" "Battery critically low!" "Battery level is  {battery_level}%!" 
paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga  

elif [ $battery_level -le 6 -a $STATUS = $NOT_CHARGING ] #Hybrid Sleep
    	then
/usr/bin/notify-send -i "$ICONL" "System about to suspend!" "Battery level is ${battery_level}%!" 
	 paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga 
sleep 2s
/usr/bin/notify-send -i "$ICONL" "5 seconds before suspend!"
paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga 

sleep 5s
systemctl hybrid-sleep
```

As I said before in my initial post, the message "Battery critically low!"  is displayed with that sound each a few seconds at and below the temperature 10, but when the other temperature of 6 is reached that should trigger hybrid sleep, nothing happens.

But if 6 is replaced with something bigger than 10, it works. 

My solutions is to use two separate scripts running in parallel at startup (with two desktop files needed in Solus) for the two different actions.

Also, I could very well use a single script that would only trigger the critical action, and it would surely be satisfactory, especially coupled with the `PercentageLow` setting in `/etc/UPower/UPower.conf`, which works ok. 

My battery report gets stuck at the level of `PercentageCritical`, but `PercentageLow` level is reported just fine. As at `PercentageCritical` it gets stuck and the applet even crashes, it never gets to `PercentageAction`, which is why I need these scripts. And, in order to use them properly, I had to set those values as low as possible, so they are never reached, in order to avoid interference with the scripts, `PercentageCritical=2` and `PercentageAction=1`.

**Comment by jerrinfrncs** [comment]
I believe the problem is the way you have edited the original script. If you are using the above script then swap the elifs 

```
elif [ $battery_level -le 6 -a $STATUS = $NOT_CHARGING ] #Hybrid Sleep
    	then
         /usr/bin/notify-send -i "$ICONL" "System about to suspend!" "Battery level is ${battery_level}%!" 
	 paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga 
         sleep 2s
         /usr/bin/notify-send -i "$ICONL" "5 seconds before suspend!"
          paplay /usr/share/sounds/freedesktop/stereo/dialog-warning.oga 

           sleep 5s
           systemctl hybrid-sleep

          elif [ $battery_level -le 10 -a $STATUS = $NOT_CHARGING ] #Battery Low 
         then
        /usr/bin/notify-send -i "$ICONL" "Battery critically low!" "Battery level is  {battery_level}%!" 
        paplay /usr/share/sounds/freedesktop/stereo/dialog-information.oga
```

Now it will work. The logic will work if you place elif's in order of increasing battery levels.

**Comment by jerrinfrncs** [comment]
problem in modified script. Issue closed.

**Comment by cipricus** [comment]
Testing it again it works!

Thank you!

**Comment by jerrinfrncs** [comment]
You are Welcome and thanks for testing.
