### ISSUE TITLE
Why the Exec line in the desktop file has that form?

### ISSUE THREAD

**Issue by cipricus** [jerrinfrncs/batterynotif#2]
If I am not imposing too much: I see that the desktop file you provided has the form:

```
[Desktop Entry]
Name=Battery Notifier 
Exec=/bin/bash -c 'for f in ~/.config/autostart/scripts/filename; do eval "$f&"; done'
Type=Application
```

Why does the Exec line need that form, why not simply `Exec=/bin/bash -c ~/.config/autostart/scripts/filename` ?

**Comment by jerrinfrncs** [comment]
Thanks for the suggestion. I believe that should be enough. I wasn't familiar with .desktop files. Will update file after testing.

**Comment by jerrinfrncs** [comment]
Updated. Closing issue.
