### ISSUE TITLE
Continuous beep and notifications on upper battery level.

### ISSUE THREAD

**Issue by cipricus** [jerrinfrncs/batterynotif#5]
This regards this part:
```

if [ $battery_level -ge 80 -a $STATUS = 1 ] #battery Charged
    	then
        	/usr/bin/notify-send -i "$ICONH" "Battery Charged" "Battery level is ${battery_level}%!" 
	paplay /usr/share/sounds/freedesktop/stereo/complete.oga
```

When the pc is connected to a power-source and the upper level is reached the script triggers repeated sound and text notifications (at bout 30 seconds interval) until the power source is disconnected.

That might be useful in some cases but in most cases it's very annoying.

Even when it is useful, a single beep+notification would suffice, or one that appears at bigger intervals.

(I think that removing all that part destroys the script; for my own use I did this:

```
if [ $battery_level -ge 100 -a $STATUS = 1 ] #battery Charged
		then
			continue
```

)

**Comment by cipricus** [comment]
I find even more preferable adding a long delay between those notifications.

For example, `sleep 120m` after the  `notify-send` and `paplay` lines of the discussed part of the script.

**Comment by jerrinfrncs** [comment]
I have set it at 80% to increase battery life. The user of the script is free to modify. I will add a comment saying that it is optional.
